name: Package Splunk Add-On, Run AppInspect, Release

on:
  pull_request:
    branches: [ $default-branch ]
    types: [opened, reopened, synchronize]
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  call-workflow:
    uses: splunk-platform-apps/.github/.github/workflows/build-appinspect-release.yml@repo-workflows
