name: Create Repo from Issue

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write

jobs:
  handle-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Debug payload
        run: echo '${{ toJson(github.event.issue) }}'
        
      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          issue-body: ${{ github.event.issue.body }}
          template-path: .github/ISSUE_TEMPLATE/component_request.yaml

      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > issue-form.json

      - run: cat issue-form.json
