name: Docs Linting

on: workflow_call

jobs:
  readme-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install vale crudini
          echo $GITHUB_WORKSPACE
      - name: Create Vale configuration file
        run: |
          # Initialize the .vale.ini file and set general configurations
          crudini --set .vale.ini '' StylesPath .github/styles
          crudini --set .vale.ini '' MinAlertLevel error

          # Add other packages
          crudini --set .vale.ini '' Packages Microsoft

          # Add the section for Markdown files and specify the custom style
          # TODO depending on the structure might be based on different styles
          crudini --set .vale.ini '*.md' BasedOnStyles 'SplunkCommunity, Microsoft'
      - name: Check whether root README exists
        run: |
          if [ ! -f README.md ]; then
            echo "README.md file is missing"
            exit 1
          fi
        working-directory: $GITHUB_WORKSPACE
      - name: Check whether docs exists and contains a README
        run: |
          if [ -d "./docs" ]; then
            echo "Folder exists."
            if [ ! -f "./docs/readme.md" ]; then
              echo "docs/readme.md file is missing"
              exit 1
            fi
          else
            echo "Folder 'docs' does not exist."
            exit 1
          fi
        working-directory: $GITHUB_WORKSPACE
      - name: Run Vale and Capture Output
        run: |
          # Download and install packages
          vale sync
          # Execute
          vale --output=JSON docs/*.md > vale-report.json || true

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: docs-linting-report
          path: vale-report.json
